grain-lang/grain-lang.org

- source/constructs/bindings.md
> Add binding docs

- source/index.md
> Fix typo in documentation introduction

- src/guide/basics.md
Hi! I saw the age was not consistent in the Basics example so I edited it.  Also, there is a minor typo in the Number Operations :) Hope this helps!
> Update age in Basics example

- src/stdlib/list.md
This is just waiting for https://github.com/grain-lang/grain/issues/84 to land.
> Update list stdlib doc

- themes/grain/layout/index.ejs
- themes/grain/source/js/main.js
> Keep nav scroll position across page loads

- scripts/hr.js
- themes/grain/source/css/style.scss
> Add header links

- docs_config.yml
- src/stdlib/option.md
- src/stdlib/pervasives.md
I guess I probably should have written the Option stdlib docs 😄
> docs: Add option document for stdlib

- src/stdlib/array.md
- src/stdlib/list.md
- src/stdlib/pervasives.md
> Update docs for grain-lang/grain#208

- src/guide/imports_exports.md
- src/guide/lists.md
- src/stdlib/array.md
- src/stdlib/int64.md
- src/stdlib/list.md
This is to accompany https://github.com/grain-lang/grain/pull/232.
> Update library paths

- src/stdlib/pervasives.md
Didn't include the additional math operations since we'll have syntax for them very soon.
> Update Pervasives docs

- src/stdlib/list.md
> Document List.drop and List.dropWhile

- docs_config.yml
- src/stdlib/map.md
> Document Map stdlib

- src/stdlib/list.md
- src/stdlib/map.md
> Add docs for new Map and List methods

- src/constructs/bindings.md
- src/constructs/boxes.md
- src/guide/basics.md
- src/guide/data_types.md
- src/guide/hello_world.md
- src/guide/imports_exports.md
- src/guide/lists.md
- src/guide/mutation.md
- src/guide/pattern_matching.md
- src/stdlib/array.md
- src/stdlib/list.md
- src/stdlib/pervasives.md
- src/stdlib/sys/file.md
- src/stdlib/sys/process.md
For https://github.com/grain-lang/grain/pull/389.
> Update comment syntax in all code examples

- src/guide/basics.md
- src/guide/functions.md
- src/stdlib/result.md
@ospencer I went through the website and caught a few things.
> Some comments syntax and small cleanup

- src/guide/data_types.md
- src/guide/imports_exports.md
- src/guide/pattern_matching.md
- src/stdlib/pervasives.md
- src/stdlib/sys/file.md
- src/stdlib/sys/process.md
Support for https://github.com/grain-lang/grain/pull/394.
> Update enum and record syntax across the site

- src/guide/data_types.md
Based on discussion on discord
> Update data_types.md: remove extraneous `=`

- src/getting_grain.md
Doc updates for https://github.com/grain-lang/grain/pull/413
> Doc updates for prepare

- src/getting_grain.md
> add windows note to website too

- src/stdlib/map.md
> Add docs for stdlib Map.update, fix Map.get

- src/stdlib/array.md
- src/stdlib/list.md
I like Options, I hear you look Options. Now everyone can like Options.
Closes #146
> Update stdlib docs to match Option returning methods

- src/stdlib/array.md
- src/stdlib/list.md
Whoa, we really fell behind!
Closes #145
> Sync up Array & List with everything added

- docs_config.yml
- src/stdlib/set.md
I hope I didn't make a typo or forget a thing 😄.
Closes #155.
> Document Set stdlib

- docs_config.yml
- src/stdlib/char.md
> Document char

- src/stdlib/string.md
Buddy for https://github.com/grain-lang/grain/pull/494
> Fix string argument order

- src/stdlib/string.md
> Document String.indexOf, String.explode, String.implode

- src/constructs/bindings.md
- src/guide/functions.md
- src/guide/lists.md
- src/guide/mutation.md
- src/stdlib/option.md
- src/stdlib/result.md
Thought I'd flesh a few things out following a cursory pass through the docs. Please let me know if anything I added is inaccurate! 🙂
> Flesh out docs a bit

- docs_config.yml
- src/stdlib/range.md
> feat: Document Range

- docs_config.yml
- src/stdlib/queue.md
> feat: Document Queue

- docs_config.yml
- src/stdlib/stack.md
> feat: Document Stack

- src/getting_grain.md
Probably needs some cleanup by @ospencer
> Add Packaged Grain to the Getting Grain page

- index.html
- stylesheets/style.css
Definitely a bit of a hack job, but gets the job done:
> feat: Show nav links on mobile

- src/editor_setup.md
@ospencer is there a better way to say this?
> Add note about binary location for vscode extension

- index.html
We link the Wasm Summit talk in the post too.
> banner to release blog post

- themes/grain/source/css/style.scss
Not a perfect fix, but makes the page viewable.
> fix: Make main blog page mobile responsive

- src_blog/_posts/New-Release-Grain-v0.3.0-Barley.md
> fix: Update Grain talk link

- src/guide/functions.md
> fibonacci should use n for n <= 1

- src/constructs/functions.md
This won't show up in the sidebar in the preview since we hid it for now.
> feat: Add docs on functions

- src/getting_grain.md
> Improve instructions for Getting Grain on Windows

- src/stdlib/range.md
Hi!
See [Range.map PR](https://github.com/grain-lang/grain/pull/674).
> feat: add doc on Range.map

- src/stdlib/queue.md
- src/stdlib/stack.md
ref https://github.com/grain-lang/grain/pull/647
> feat: add docs for `size` in Queue & Stack

- src/stdlib/bytes.md
> feat: Document Bytes stdlib

- src/guide/pattern_matching.md
- src/stdlib/option.md
- src/stdlib/result.md
This PR adds a few small additions to text about Option and Result, including:
- Updating pattern matching to show how Option and Result are used
- Updating Option to show how to create a new Option
- Updating Result to show how to create a new Result
Signed-off-by: Matt Butcher <matt.butcher@microsoft.com>
> feat: Added more documentation about Option and Result

- index.html
- src_blog/_posts/Grain-Hearts-Hacktoberfest.md
- src_blog/_posts/Grain-State-of-the-Union-2020.md
- src_blog/_posts/New-Release-Grain-v0.3.0-Barley.md
- themes/grain/layout/_partial/footer.ejs
- themes/grain/layout/index.ejs
- themes/grain/source/css/style.scss
> fix discord link

- src/stdlib/stack.md
- themes/grain/source/css/style.scss
Also adds a deprecation to the website to check it out.
> fix: Add warning colors to blockquotes produced by deprecated attrs

- scripts/syntaxHighlight.js
- src/guide/pattern_matching.md
~~Draft for those sweet sweet website previews.~~
It appears to work!
> fix: Only highlight code blocks marked language grain

- src/getting_grain.md
Updates for the node 16 and npm PRs
> chore: Update yarn references to npm

- src/tooling/graindoc.md
Hi grain team, the new docs on docs are great but I found the last sentence confusing. I hope this change is both correct and clarifies!
> chore: Clarify @section in graindocs

- src/getting_grain.md
- src/stdlib/array.md
- src/stdlib/buffer.md
- src/stdlib/bytes.md
- src/stdlib/char.md
- src/stdlib/int32.md
- src/stdlib/int64.md
- src/stdlib/list.md
- src/stdlib/number.md
- src/stdlib/option.md
- src/stdlib/path.md
- src/stdlib/pervasives.md
- src/stdlib/queue.md
- src/stdlib/regex.md
- src/stdlib/result.md
- src/stdlib/runtime/atof/common.md
- src/stdlib/runtime/atof/decimal.md
- src/stdlib/runtime/atof/lemire.md
- src/stdlib/runtime/atof/parse.md
- src/stdlib/runtime/atof/slow.md
- src/stdlib/runtime/atof/table.md
- src/stdlib/runtime/atoi/parse.md
- src/stdlib/runtime/numberUtils.md
- src/stdlib/runtime/unsafe/conv.md
- src/stdlib/stack.md
The JS grain binaries are failing with a stack overflow when trying to generate docs for the stdlib. So this is manual generation of the commit our CI usually would.
> chore: Update website for grain-v0.5.5

- playground_src/scripts/playground.js
We'll maybe want to add a CI check that ensures the code is formatted.
> chore: Format playground src

- playground_src/scripts/compiler.js
As in #371 we added the `wasm-feature-detect` library, we might as well also test for `bulk-memory` and in browser's that don't support it dissable it to improve the range of browser's we support. This pr also better set's us up for future toggles.
> feat: Disable bulk memory when not supported

- src/guide/collections_and_libraries.md
- src/guide/pattern_matching.md
Just noticed a couple of small typos as I was reading through the docs
> chore: Fix small typos in docs

- index.html
- playground_src/index.html
- themes/grain/layout/layout.ejs
This PR switches from Google Analytics to Plausible. This solution offers better privacy for our website visitors and supports good open source work.
> feat: Switch to Plausible analytics
