src/getting_grain.md
I was following the instructions and realized that `yarn compiler:build` doesn't exist, instead it should be `yarn compiler build`
=> docs: Update compiler build command

src/getting_grain.md
Forgot to update this in https://github.com/grain-lang/grain-lang.org/pull/71
=> docs: Fix typo in compiler build explanation

package-lock.json, package.json, scripts/hr.js, scripts/syntaxHighlight.js
I was having native build troubles so I started diving into vscode-textmate and discovered that they removed the native dependency `oniguruma` in 5.x. In their tests, they actually use `onigasm` which is just that library compiled to WASM.
I needed to do some other changes to make sure everything worked since vscode-textmate initialization is all async now. But I ran a diff on the output and everything looks the same!
=> Switch to onigasm to avoid native build problems

src/getting_grain.md
Once https://github.com/grain-lang/grain/pull/395 lands, we don't need people to install cmake first.
=> Remove cmake requirement

src/guide/lists.md
I didn't see any internal links in the docs, so maybe there's a reason why this isn't linked 😬
=> Add hyperlink to list docs.

src/constructs/boxes.md, src/stdlib/pervasives.md
I searched for `^` and `unbox` and removed the caret syntax to go with my other PR.
=> update docs to remove ^ as unbox alias

src/stdlib/array.md
This PR adds documentation for the `Array.find` & `Array.findIndex` functions.
Closes #118.
=> Document `Array.find` & `Array.findIndex`.

src/constructs/bindings.md
I realized that this actually hasn't been valid syntax for quite some time.
=> Fix syntax of isEven and isOdd example

index.html
After the links to individual talks are live, we can update the banner again to point to that.
=> Update banner to point to the wasm summit

docs_config.yml, src/constructs/overview.md
This page was really old and doesn't really serve a purpose. Deleting it seems like the best thing to do.
=> chore: Remove overview from constructs

scripts/syntaxHighlight.js
I double checked that all of the examples are marked as language `grain`.
=> fix: Only syntax highlight code blocks marked as language grain

index.html, stylesheets/style.css
It's a bit of a long story, but I was looking at the Google PageSpeed insights for Grain, and I saw that our mobile FCP rendering time was not stellar:
Looking at the opportunities identified by the tool, I saw that we are blocking the page renders on CSS loads (and FontAwesome):
This PR should defer those loads and hopefully allow the rendering to happen faster.
=> Defer CSS loading

themes/grain/source/css/style.scss
Makes code blocks more readable.
=> feat: Accessible inline code blocks

src/guide/pattern_matching.md
This adds basic documentation for `when` guards in `match`es. I mainly used the parser and trial-and-error to figure this out, so I may have gotten some things wrong or incomplete.
Closes #102 
Signed-off-by: Matt Butcher <matt.butcher@microsoft.com>
=> feat: Document guards

themes/grain/source/css/style.scss
fix #218, mobile nav scrollbar visible on chrome desktop
=> fix mobile nav visibility on desktop

themes/grain/source/css/style.scss
Pulled this out of #240 - styling for the `<details>` blocks produced by graindoc.
=> feat: Add styling for history details

src/stdlib/string.md
I understand that this API will change once Buffers land, but I would love to see us try to keep the documentation in sync with `main`.
=> feat: Add documentation for String.encode and String.decode

index.html, themes/grain/layout/_partial/footer.ejs, themes/grain/layout/_partial/hero.ejs
We can discuss whether this is a good change or not, but I thought it might be nice to have a link to the Discord page with the other socials in the header. Currently, there are two links to the Discord page: one mention in the docs, and a link if you scroll down on the homepage. This makes it much more prominent on the website.
Preview:
Closes #185 .
=> feat: Add link to Discord in hero with other socials

.github/workflows/release.yml, src/stdlib/.gitignore
This adds a workflow that is triggered by a [workflow_dispatch](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch) event, which is a manual event that can be triggered through the GitHub UI or via an API call. I plan to implement the API call into the release flow of the main Grain repo.
You can see my experiments with this at https://github.com/phated/grain-lang.org/commit/3acccdf14414e6284d470eb99011843dbf1bbd31 and https://github.com/phated/grain-lang.org/commit/13cf1d4d0afdf78e14a78f60d284f6575361147a (I just used tags that already existed so the diffs might look confusing - like going from v0.4.2 to v0.4.1 - but you can see how it works).
=> feat: Add workflow to update website based on a tag

blog_config.yml, package-lock.json, package.json
Added support for an rss2 feed and atom feed using https://github.com/hexojs/hexo-generator-feed.
solves to #206.
Routes are:
https://grain-lang.org/blog/rss2.xml
https://grain-lang.org/blog/atom.xml
=> feat: Add Support For rss and atom

src/guide/data_types.md
=> 'Veggies' -> 'Veggie'

.github/workflows/release.yml
Relies on simplified version printing.
This solves some missing directory errors that I saw in my release fork stuff.
=> feat: Use grain doc to generate updated docs

docs_config.yml, src/basic_types.md, src/builtin_types.md
Since these are part of the compiler, they aren't actually part of the stdlib (or Pervasives).
=> chore: Add docs for basic types

src_blog/_posts/New-Release-Grain-v0.5-Durum.md
I clicked on these and they didn't link because our generator capitalizes the hashes
=> fix: Correctly capitalize hash-links in blog post

src/guide/lists.md
Usage of mutable variable before this concept is introduced gives a misleading impression of the language.
=> fix: Avoid shadowing concept in List guide

blog_config.yml, docs_config.yml
Graindoc spits out GFM, so we should use that here too.
=> feat: Enable GitHub Flavored Markdown

docs_config.yml
We originally put the additional number libraries at the bottom to push people towards using `Number`, but now that we've got so many libraries I think it makes far more sense to alphabetize them.
=> feat: Alphabetize stdlib sidebar

package-lock.json, package.json
When trying to install the dependencies on a Mac M1, I found that `hexo-renderer-scss` didn't install on a default setup. This switches the unmaintained plugin for a (likely just as unmaintained) plugin that uses dartsass.
I don't actually know where we use scss so I'm looking to @ospencer to double check the styling.
I also updated vscode-textmate as I need the newest version for the playgound.
To cap it all off, I generated the lockfile with a newer npm so we have lockfile v2.
=> chore: Dependency updates

playground_src/scripts/compiler.js
I noticed that if I try to compile an empty file, it succeeds but then the WASI runner fails (which then makes the user unable to compile without a refresh).
This temporary fix at least responds with an error so the recompile can be performed.
=> fix: Respond with the error message if the wasm run fails

docs_config.yml
I believe these were new in 0..5.4
=> chore: Add immutablemap & immutableset to sidebar

docs_config.yml
This adds ImmutableArray (added in 0.5.8) to the sidebar.
=> chore: Add ImmutableArray to the sidebar

src/tooling/graindoc.md
This pr adds documentation on the `@throws` graindoc property.
=> feat: Add `@throws` to graindoc documentation

package-lock.json, package.json
This updates the playground for Grain v0.5.8
I've tested:
```grain
import Number from "number"
print(Number.parse("1234"))
```
And it seems to work!
=> chore: Upgrade playground to Grain v0.5.8

package-lock.json, package.json
This upgrades the playground for v0.5.9 - I didn't test locally, will test on the netlify deploy.
=> chore: Update playground for Grain v0.5.9

.github/workflows/release.yml, src/getting_grain.md
This adds docs for getting the preview binaries added in https://github.com/grain-lang/grain/pull/1777
=> chore: Add preview section to installation docs

src/tooling/graindoc.md
This pr adds in examples for multiline grain doc examples, it also removes the section attribute as was done in v0.6.0.
I would also like to refactor the module section to line up with v0.6.0 but I am wondering what the best way of doing that would be given its no longer really an attribute and the docs are written in an attribute first way.
=> chore: Update Graindoc Docs

docs_config.yml, src/stdlib/DOM.md
It will be some time before we offer this capability as a part of the standard library, so removing it for now.
=> chore: Remove DOM docs

.github/workflows/release.yml, src/builtin_types.md, src/getting_grain.md, src/guide/collections_and_libraries.md, src/guide/loops.md, src/guide/mutation.md, src/index.md, src/tooling/grain_cli.md
As we have decided to hold the new website for a little bit, I figured it would make sense to backport a few of the documentation improvements and fixes to the current version.
Changes:
* On Release we now clean the `stdlib` docs
* This gets rid of removed modules `ImmutableMap`
* Add the missing `Range` datatype
* Mention node `v22` over `v16` as we're upgrading
* Correct some `0.5` syntax that was missed
* Update the cli options table
One additional note is the `asdf` release still points to `0.4.6` but I'm waiting until we decide how to handle it with the v2 version before updating (Our release process won't update that). 
This is on hold until the next release because of the `v22` note.
=> feat: Backport doc improvements for `0.7`
